version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./assignment:/var/www/html
    ports :
      - 80:80
  db:
    image: mysql
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: try
      MYSQL_DATABASE: assignment1
    ports:
      - 3306:3306
